version: '3'
services:
  mymarkdown:
    image: govargo/mymarkdown:20180108
#    command: tail -f /dev/null
    ports:
      - 8080:8080
      - 9005:9005
    volumes:
      - "./mymarkdown:/usr/src/app"
